In [3]:
# I kept only the essential columns for diabetic analysis
columns_to_keep = [
    'Description',
    'Data.Sugar Total',
    'Data.Carbohydrate',
    'Data.Fiber',
    'Data.Kilocalories',
    'Data.Fat.Saturated Fat'
]

df = df[columns_to_keep]
df.head()

,Description,Data.Sugar Total,Data.Carbohydrate,Data.Fiber,Data.Kilocalories,Data.Fat.Saturated Fat
0,"BUTTER,WITH SALT",0.06,0.06,0.0,717,51.368
1,"BUTTER,WHIPPED,WITH SALT",0.06,0.06,0.0,717,50.489
2,"BUTTER OIL,ANHYDROUS",0.00,0.00,0.0,876,61.924
3,"CHEESE,BLUE",0.50,2.34,0.0,353,18.669
4,"CHEESE,BRICK",0.51,2.79,0.0,371,18.764

In [4]:
# Identifying  missing values in each column
df.isnull().sum()

Description               0
Data.Sugar Total          0
Data.Carbohydrate         0
Data.Fiber                0
Data.Kilocalories         0
Data.Fat.Saturated Fat    0
dtype: int64

In [5]:
# Cleaned dataset before adding labels saved
df.to_csv("../data/cleaned/food_cleaned.csv", index=False)

In [ ]:
# Diabetic suitability based on 4 NHS references
def is_suitable(row):
    sugar = row['Data.Sugar Total']
    carbs = row['Data.Carbohydrate']
    sat_fat = row['Data.Fat.Saturated Fat']

    if pd.isnull(sugar) or pd.isnull(carbs) or pd.isnull(sat_fat):
        return None  # Safe fallback for missing values

    if sugar > 15 or carbs > 45 or sat_fat > 5:
        return 0  # Not suitable for diabetics
    else:
        return 1  # Suitable

# Logic
df['Diabetic_Suitability'] = df.apply(is_suitable, axis=1)

# View results
df[['Description', 'Data.Sugar Total', 'Data.Carbohydrate', 'Data.Fat.Saturated Fat', 'Diabetic_Suitability']].head()

,Description,Data.Sugar Total,Data.Carbohydrate,Data.Fat.Saturated Fat,Diabetic_Suitability
0,"BUTTER,WITH SALT",0.06,0.06,51.368,0
1,"BUTTER,WHIPPED,WITH SALT",0.06,0.06,50.489,0
2,"BUTTER OIL,ANHYDROUS",0.00,0.00,61.924,0
3,"CHEESE,BLUE",0.50,2.34,18.669,0
4,"CHEESE,BRICK",0.51,2.79,18.764,0

In [2]:
# Save final cleaned and labelled dataset
df.to_csv("../data/cleaned/food_labelled.csv", index=False)